### PR TITLE
bug: make export respect context

### LINKED ISSUE #67: [BUG] Cannot set context in crane export
**What version of crane are you running, and what are your clutsters+platform**

./crane version
crane:
	Version: v0.0.3
crane-lib:
	Version: v0.0.5

**What did you expect to happen?**

Setting context this way doesn't work:
Crane export --context some_context

you have to switch to this context before exporting for crane to export properly.

**What actually happened?**

getting empty export folder as the namespace is not found (wrong context).

**Please include any relevant logs or errors**

### PR DESCRIPTION
**Pull request by djzager**
Several of the methods from cli-runtime's genericclioptions package
expect for the AddFlags() method to be called first. Calling AddFlags()
first should allow us to remove some options and rely on cli-runtime to
handle cluster/namespace/context/auth/etc for us.

Fixes #67

### CODE REVIEW

**Review by jmontleon — COMMENTED** [review]
ACK from me. I think your change makes sense. I'm not sure my two cents are worth much at the moment, been pretty out of the loop.

File: cmd/export/export.go [hunk 1]
```diff
@@ -18,161 +16,49 @@ import (
...
-}
-
-type Flags struct {
-	ExportDir string `mapstructure:"export-dir"`
-	Context   string `mapstructure:"context"`
-	Namespace string `mapstructure:"namespace"`
+	rawConfig api.Config
+	exportDir string `mapstructure:"export-dir"`
+	// TODO(djzager): how do we handle viper + k8s cli options?
+	namespace string
```
Comment (djzager) [inline cmd/export/export.go:30]: @sseago brought up, and we need to answer...how are we going to handle the flags-file overrides. It's not immediately obvious how to make that work.

**Comment by djzager** [comment]
Running through the different configuration scenarios.

### Defaults

```bash
$ ./crane export
INFO[0000] adding resource: configmaps to the list of GVRs to be extracted
INFO[0000] adding resource: serviceaccounts to the list of GVRs to be extracted
INFO[0000] adding resource: services to the list of GVRs to be extracted
INFO[0000] adding resource: secrets to the list of GVRs to be extracted
INFO[0000] adding resource: endpoints to the list of GVRs to be extracted
INFO[0003] adding resource: endpointslices to the list of GVRs to be extracted
W1222 16:37:53.098729 1795742 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
INFO[0003] Writing objects of resource: configmaps to the output directory
INFO[0003] Writing objects of resource: serviceaccounts to the output directory
INFO[0003] Writing objects of resource: services to the output directory
INFO[0003] Writing objects of resource: secrets to the output directory
INFO[0003] Writing objects of resource: endpoints to the output directory
INFO[0003] Writing objects of resource: endpointslices to the output directory

$ tree -a export
export
├── failures
│   └── default
└── resources
    └── default
        ├── ConfigMap_default_kube-root-ca.crt.yaml
        ├── Endpoints_default_kubernetes.yaml
        ├── EndpointSlice_default_kubernetes.yaml
        ├── Secret_default_default-token-xjsz4.yaml
        ├── ServiceAccount_default_default.yaml
        └── Service_default_kubernetes.yaml

4 directories, 6 files
```

### Only command line

```
$ ./crane export --export-dir export2
INFO[0000] adding resource: serviceaccounts to the list of GVRs to be extracted
INFO[0000] adding resource: services to the list of GVRs to be extracted
INFO[0000] adding resource: configmaps to the list of GVRs to be extracted
INFO[0000] adding resource: endpoints to the list of GVRs to be extracted
INFO[0000] adding resource: secrets to the list of GVRs to be extracted
INFO[0003] adding resource: endpointslices to the list of GVRs to be extracted
W1222 16:41:43.571251 1799365 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
INFO[0003] Writing objects of resource: serviceaccounts to the output directory
INFO[0003] Writing objects of resource: services to the output directory
INFO[0003] Writing objects of resource: configmaps to the output directory
INFO[0003] Writing objects of resource: endpoints to the output directory
INFO[0003] Writing objects of resource: secrets to the output directory
INFO[0003] Writing objects of resource: endpointslices to the output directory

$ ./crane export --namespace foo --export-dir export2
W1222 16:47:22.352651 1804556 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

$ ./crane export --context bar --export-dir export2
Error: invalid configuration: context was not found for specified context: bar

$ tree -a export2
export2
├── failures
│   ├── default
│   └── foo
└── resources
    ├── default
    │   ├── ConfigMap_default_kube-root-ca.crt.yaml
    │   ├── Endpoints_default_kubernetes.yaml
    │   ├── EndpointSlice_default_kubernetes.yaml
    │   ├── Secret_default_default-token-xjsz4.yaml
    │   ├── ServiceAccount_default_default.yaml
    │   └── Service_default_kubernetes.yaml
    └── foo

6 directories, 6 files
```

### Only flags-file

```bash
$ cat craneConfig.yaml
context: kind-src
namespace: guestbook
export-dir: export3

$ ./crane export --flags-file craneConfig.yaml
INFO[0000] Using config file: craneConfig.yaml
INFO[0000] adding resource: services to the list of GVRs to be extracted
INFO[0000] adding resource: configmaps to the list of GVRs to be extracted
INFO[0000] adding resource: pods to the list of GVRs to be extracted
INFO[0000] adding resource: secrets to the list of GVRs to be extracted
INFO[0000] adding resource: endpoints to the list of GVRs to be extracted
INFO[0000] adding resource: serviceaccounts to the list of GVRs to be extracted
INFO[0000] adding resource: deployments to the list of GVRs to be extracted
INFO[0001] adding resource: replicasets to the list of GVRs to be extracted
INFO[0003] adding resource: endpointslices to the list of GVRs to be extracted
W1222 16:52:51.372073 1810072 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
INFO[0003] Writing objects of resource: services to the output directory
INFO[0003] Writing objects of resource: configmaps to the output directory
INFO[0003] Writing objects of resource: pods to the output directory
INFO[0003] Writing objects of resource: secrets to the output directory
INFO[0003] Writing objects of resource: endpoints to the output directory
INFO[0003] Writing objects of resource: serviceaccounts to the output directory
INFO[0003] Writing objects of resource: deployments to the output directory
INFO[0003] Writing objects of resource: replicasets to the output directory
INFO[0003] Writing objects of resource: endpointslices to the output directory

$ tree -a export3
export3
├── failures
│   └── guestbook
└── resources
    └── guestbook
        ├── ConfigMap_guestbook_kube-root-ca.crt.yaml
        ├── Deployment_guestbook_frontend.yaml
        ├── Deployment_guestbook_redis-master.yaml
        ├── Deployment_guestbook_redis-slave.yaml
        ├── Endpoints_guestbook_frontend.yaml
        ├── Endpoints_guestbook_redis-master.yaml
        ├── Endpoints_guestbook_redis-slave.yaml
        ├── EndpointSlice_guestbook_frontend-jt6lp.yaml
        ├── EndpointSlice_guestbook_redis-master-4jddk.yaml
        ├── EndpointSlice_guestbook_redis-slave-7tqvp.yaml
        ├── Pod_guestbook_frontend-5fd859dcf6-gpzfw.yaml
        ├── Pod_guestbook_frontend-5fd859dcf6-knp9m.yaml
        ├── Pod_guestbook_frontend-5fd859dcf6-qn2rv.yaml
        ├── Pod_guestbook_redis-master-55d9747c6c-vgzg7.yaml
        ├── Pod_guestbook_redis-slave-5c6b4c5b47-ppcqs.yaml
        ├── Pod_guestbook_redis-slave-5c6b4c5b47-shchm.yaml
        ├── ReplicaSet_guestbook_frontend-5fd859dcf6.yaml
        ├── ReplicaSet_guestbook_redis-master-55d9747c6c.yaml
        ├── ReplicaSet_guestbook_redis-slave-5c6b4c5b47.yaml
        ├── Secret_guestbook_default-token-qrvsm.yaml
        ├── ServiceAccount_guestbook_default.yaml
        ├── Service_guestbook_frontend.yaml
        ├── Service_guestbook_redis-master.yaml
        └── Service_guestbook_redis-slave.yaml

4 directories, 24 files
```

### Combination

```bash
$ kubectl config current-context
kind-dest

$ cat craneConfig.yaml
# context: kind-src
namespace: guestbook
export-dir: export3

$ ./crane export --flags-file craneConfig.yaml --export-dir export4
INFO[0000] Using config file: craneConfig.yaml
INFO[0000] adding resource: configmaps to the list of GVRs to be extracted
INFO[0000] adding resource: serviceaccounts to the list of GVRs to be extracted
INFO[0000] adding resource: secrets to the list of GVRs to be extracted
W1222 16:55:19.571931 1812602 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
INFO[0003] Writing objects of resource: configmaps to the output directory
INFO[0003] Writing objects of resource: serviceaccounts to the output directory
INFO[0003] Writing objects of resource: secrets to the output directory

$ ./crane export --flags-file craneConfig.yaml --export-dir export4 --namespace foo
INFO[0000] Using config file: craneConfig.yaml
W1222 16:55:42.541886 1812953 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

$ tree -a export4
export4
├── failures
│   ├── foo
│   └── guestbook
└── resources
    ├── foo
    └── guestbook
        ├── ConfigMap_guestbook_kube-root-ca.crt.yaml
        ├── Secret_guestbook_default-token-d5qpj.yaml
        └── ServiceAccount_guestbook_default.yaml

6 directories, 3 files
```

This matches my expectations for behavior.

File: cmd/export/export.go [hunk 2]
```diff
@@ -18,161 +16,48 @@ import (
...
-	addFlagsForOptions(&o.cobraFlags, cmd)
-
-	return cmd
-}
-
-func addFlagsForOptions(o *Flags, cmd *cobra.Command) {
-	cmd.Flags().StringVarP(&o.ExportDir, "export-dir", "e", "export", "The path where files are to be exported")
-	cmd.Flags().StringVar(&o.Context, "context", "", "The kube context, if empty it will use the current context. If --namespace is set it will take precedence")
-	cmd.Flags().StringVarP(&o.Namespace, "namespace", "n", "", "The kube namespace to export.")
-	cmd.Flags().StringVar(&o.User, "as-user", "", "The user to impersonation.")
```
Comment (shawn-hurley) [inline cmd/export/export.go:125]: Are we losing this ability with this PR?

Comment (djzager) [reply cmd/export/export.go:125]: We are losing the `as-user` flag, but is this the same as `user` in `kubectl`? This is what our `--help` looks like with this change:

```
$ ./crane export --help
Export the namespace resources in an output directory

Usage:
  crane export [flags]

Flags:
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string               Default cache directory (default "/home/dzager/.kube/cache")
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
  -e, --export-dir string              The path where files are to be exported (default "export")
  -h, --help                           help for export
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests.
  -n, --namespace string               If present, the namespace scope for this CLI request
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                  The address and port of the Kubernetes API server
      --tls-server-name string         Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use

Global Flags:
      --debug               Debug the command by printing more information
  -f, --flags-file string   Path to input file which contains a yaml representation of cli flags. Explicit flags take precedence over input file values.
```

Does `--user string                    The name of the kubeconfig user to use` give us what we need here?

**Review by shawn-hurley — APPROVED** [review]
Looks ok to me, as long as we update the folks that are using us the change in the CLI flags
